apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phone-settings
  namespace: enterprise-ai-demo
  labels:
    app.kubernetes.io/name: enterprise-ai-demo
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
