{
  "apiVersion": "v1",
  "kind": "Service",
  "metadata":
    {
      "namespace": "enterprise-ai-demo",
      "labels": { "app.kubernetes.io/part-of": "enterprise-speech" },
      "name": "speech-tts",
    },
  "spec":
    {
      "type": "ExternalName",
      "externalName": "kuvryn-67579477-05ed-45a7-9903-c2dc7aabfac4-b4616c22.kuvryn-ai-workloads.svc.cluster.local",
      "ports": [{ "name": "http", "port": 8094, "targetPort": 8094 }],
    },
}
---
{
  "apiVersion": "v1",
  "kind": "Service",
  "metadata":
    {
      "namespace": "enterprise-ai-demo",
      "labels": { "app.kubernetes.io/part-of": "enterprise-speech" },
      "name": "speech-stt",
    },
  "spec":
    {
      "type": "ExternalName",
      "externalName": "kuvryn-0b03dce0-1eac-40dd-8541-59321391fac5-a46ea12d.kuvryn-ai-workloads.svc.cluster.local",
      "ports": [{ "name": "http", "port": 8093, "targetPort": 8093 }],
    },
}
---
{
  "apiVersion": "v1",
  "kind": "Service",
  "metadata":
    {
      "namespace": "enterprise-ai-demo",
      "labels": { "app.kubernetes.io/part-of": "enterprise-speech" },
      "name": "speech-tts-stream",
    },
  "spec":
    {
      "type": "ExternalName",
      "externalName": "kuvryn-9034ee12-b1c9-4b94-9cda-d1a9c6c0a366-a46ea12d.kuvryn-ai-workloads.svc.cluster.local",
      "ports": [{ "name": "http", "port": 8095, "targetPort": 8095 }],
    },
}
---
{
  "apiVersion": "v1",
  "kind": "Service",
  "metadata":
    {
      "namespace": "enterprise-ai-demo",
      "labels": { "app.kubernetes.io/part-of": "enterprise-speech" },
      "name": "speech-stt-final",
    },
  "spec":
    {
      "type": "ExternalName",
      "externalName": "kuvryn-f0e846ba-cf14-4175-a97b-acdd8703b817-a46ea12d.kuvryn-ai-workloads.svc.cluster.local",
      "ports": [{ "name": "http", "port": 8096, "targetPort": 8096 }],
    },
}
---
{
  "apiVersion": "v1",
  "kind": "Service",
  "metadata":
    {
      "namespace": "enterprise-ai-demo",
      "labels": { "app.kubernetes.io/part-of": "enterprise-speech" },
      "name": "speech-tts-novanas",
    },
  "spec":
    {
      "type": "ClusterIP",
      "ports": [{ "name": "http", "port": 8095, "targetPort": 8101 }],
    },
}
---
{
  "apiVersion": "discovery.k8s.io/v1",
  "kind": "EndpointSlice",
  "metadata":
    {
      "namespace": "enterprise-ai-demo",
      "name": "speech-tts-novanas-1",
      "labels":
        {
          "app.kubernetes.io/part-of": "enterprise-speech",
          "kubernetes.io/service-name": "speech-tts-novanas",
          "endpointslice.kubernetes.io/managed-by": "kuvryn-sync",
        },
    },
  "addressType": "IPv4",
  "ports": [{ "name": "http", "port": 8101, "protocol": "TCP" }],
  "endpoints":
    [{ "addresses": ["192.168.10.203"], "conditions": { "ready": true } }],
}
