import React, { useEffect, useState } from 'react';
type Registration={username:string;password?:string;password_saved:boolean};
type Config={revision:number;host:string;port:number;transport:string;mode:string;advertise_ip:string;registrations:Record<string,Registration>;auto_connect:boolean};
type Status={config:Config;state:string;error:string;sip_port:number;rtp_start:number;rtp_end:number};
async function call(path='',body?:unknown):Promise<Status>{const res=await fetch('/api/settings/sip'+path,body!==undefined?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined);const data=await res.json();if(!res.ok)throw new Error(data.error||'Gateway request failed');return data;}
export function SIPGateway({personas}:{personas:{config:{id:string;name:string}}[]}){
 const [status,setStatus]=useState<Status>();const [draft,setDraft]=useState<Config>();const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');
 useEffect(()=>{let active=true;const load=async()=>{try{const data=await call();if(active){setStatus(data);setDraft(old=>old||data.config);}}catch(e){if(active)setError((e as Error).message);}};void load();const timer=setInterval(load,3000);return()=>{active=false;clearInterval(timer);};},[]);
 function change(patch:Partial<Config>){setDraft(old=>old?{...old,...patch}:old);setNotice('');}
 async function action(name:'save'|'connect'|'disconnect'){if(!draft)return;setBusy(true);setError('');setNotice('');try{if(name!=='disconnect'){const saved=await call('',draft);setDraft(saved.config);setStatus(saved);}if(name!=='save'){const data=await call('/'+name,{});setStatus(data);setDraft(data.config);}setNotice(name==='save'?'Gateway settings saved.':name==='connect'?'Connection started; checking the gateway…':'Disconnected. Active phone calls have ended.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const running=!!status?.config.auto_connect;
 return <section className="sip-gateway" aria-label="SIP gateway"><div className="section-heading"><h3>SIP gateway</h3><span className="pill">{status?.state||'Loading…'}</span></div>
 <p className="muted">Connect your Hello PBX to the agent service. Each persona keeps its own phone numbers and independent conversations.</p>
 {error&&<p role="alert" className="error">{error}</p>}{status?.error&&<p role="alert" className="error">{status.error}</p>}{notice&&<p role="status">{notice}</p>}
 {draft&&<><fieldset disabled={busy||running} className="gateway-fields">
 <label>Gateway IP address<input value={draft.host} placeholder="192.168.10.50" onChange={e=>change({host:e.target.value})}/></label>
 <label>Gateway SIP port<input type="number" min={1} max={65535} value={draft.port} onChange={e=>change({port:Number(e.target.value)})}/></label>
 <label>SIP transport<select value={draft.transport} onChange={e=>change({transport:e.target.value})}><option value="udp">UDP</option><option value="tcp">TCP</option></select></label>
 <label>Connection mode<select value={draft.mode} onChange={e=>change({mode:e.target.value})}><option value="trunk">IP authenticated trunk</option><option value="register">Register each persona as an extension</option></select></label>
 <label>Agent advertised SIP / media IP<input value={draft.advertise_ip} onChange={e=>change({advertise_ip:e.target.value})}/></label>
 {draft.mode==='register'&&personas.map(a=>{const r=draft.registrations[a.config.id]||{username:'',password_saved:false};return <div key={a.config.id} className="phone-persona"><h4>{a.config.name} registration</h4><label>SIP extension<input value={r.username} onChange={e=>change({registrations:{...draft.registrations,[a.config.id]:{...r,username:e.target.value}}})}/></label><label>SIP password<input type="password" autoComplete="new-password" value={r.password||''} placeholder={r.password_saved?'Saved password · leave blank to keep':'Gateway authentication password'} onChange={e=>change({registrations:{...draft.registrations,[a.config.id]:{...r,password:e.target.value}}})}/></label><label><input type="checkbox" checked={r.password_saved} onChange={e=>change({registrations:{...draft.registrations,[a.config.id]:{...r,password_saved:e.target.checked}}})}/> Keep saved password</label><p className="quiet">Assign this extension to the same persona below. Leave the extension empty to skip registration for this persona.</p></div>;})}
 </fieldset><p className="quiet">PBX destination: {draft.advertise_ip||'agent IP'}:{status?.sip_port||5060}. Audio: UDP {status?.rtp_start||10000}–{status?.rtp_end||10199}. Allow these ports in your PBX firewall. The KW endpoint accepts your local network (192.168.10.0/24); its cluster forwarders are trusted.</p>
 <div className="gateway-actions"><button disabled={busy||running} onClick={()=>void action('save')}>Save gateway settings</button><button className="primary" disabled={busy||running} onClick={()=>void action('connect')}>{busy?'Working…':'Connect'}</button><button disabled={busy||!running} onClick={()=>void action('disconnect')}>Disconnect</button></div>
 <p className="quiet">Connect saves gateway settings and checks SIP responses. Save persona numbers below before connecting. Connections resume after an app restart. Disconnect ends active phone calls. Approvals remain spoken, with no keypad controls or caller access code.</p></>}
 </section>;
}
